name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker compose
        run: |
          docker-compose up -d
          sudo docker ps -a

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          echo "$SSH_PRIVATE_KEY" > alma.pem
          ssh -o StrictHostKeyChecking=no -i alma.pem ubuntu@44.210.140.4 'cd  /home/ubuntu/akhil,/dockerodoo'      
     
      - name: docker-compose
        run: |
          ssh -o StrictHostKeyChecking=no -i alma.pem ubuntu@44.210.140.4 'cd  /home/ubuntu/akhil,/dockerodoo && pwd && sudo docker-compose up -d'
          
      - name: Install ngnix 
        run: |
          ssh -o StrictHostKeyChecking=no -i alma.pem ubuntu@44.210.140.4 'cd  /home/ubuntu/akhil,/dockerodoo && sudo apt update -y && sudo apt install nginx -y'

      - name: nginx configuration
        run: |
          ssh -o StrictHostKeyChecking=no -i alma.pem ubuntu@44.210.140.4 'cd  /home/ubuntu/akhil,/dockerodoo && sudo cp odoo.conf /etc/nginx/sites-available/ && sudo ln -s /etc/nginx/sites-available/odoo.conf /etc/nginx/sites-enabled/ && sudo nginx -t'

      - name: Restart nginx service
        run: |
          ssh -o StrictHostKeyChecking=no -i alma.pem ubuntu@44.210.140.4 'cd  /home/ubuntu/akhil,/dockerodoo && sudo systemctl start nginx && sudo systemctl enable nginx && sudo systemctl restart nginx'
