name: Odoo Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker compose
        run: |
          docker-compose up -d
          sudo docker ps -a
      
      - name: Install ngnix 
        run: |
          sudo apt update -y
          sudo apt install nginx -y

      - name: nginx configuration
        run: |
          sudo cp odoo.conf /etc/nginx/sites-available/       
          sudo ln -s /etc/nginx/sites-available/odoo.conf /etc/nginx/sites-enabled/
          sudo nginx -t

      - name: Restart nginx service
        run: |
          sudo systemctl start nginx
          sudo systemctl enable nginx
          sudo systemctl status nginx
